### ISSUE TITLE
空录

### ISSUE THREAD

**Issue by liuqianghui** [liuqianghui/liuqianghui.github.io#2]
有空就来记录当前的经历
2017.12.30晚上3.16。位于上海。
通过看[YouTube上视频](https://www.youtube.com/channel/UCW5YeuERMmlnqo4oq8vwUpg/playlists)温习了一遍es6的东西,连接了之前记忆里不是很清晰的技术片段，只希望能越来越好，不辜负自己就够了。2018年加油。

**Comment by Yawytya** [comment]
Electron以后可能要火。
